name: Retrieve Base64 secret
on:
    workflow_dispatch:
jobs:
  decode-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: akiojin/decode-base64-github-action@v0.1.0
        id: decode-base64
        with:
            base64: ${{ secrets.TM_DEV_ENV }}
            output-path: task-manager.env
      - run: |
            cat task-manager.env
